# Generated by Django 4.2 on 2025-06-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_remove_group_members_message_is_pinned_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupmember",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="groupmember",
            name="group",
        ),
        migrations.RemoveField(
            model_name="groupmember",
            name="user",
        ),
        migrations.RemoveField(
            model_name="invitelink",
            name="group",
        ),
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="message",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="user",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_pinned",
        ),
        migrations.RemoveField(
            model_name="message",
            name="location",
        ),
        migrations.RemoveField(
            model_name="message",
            name="replied_to",
        ),
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(related_name="groups", to="chat.user"),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Friend",
        ),
        migrations.DeleteModel(
            name="GroupMember",
        ),
        migrations.DeleteModel(
            name="InviteLink",
        ),
        migrations.DeleteModel(
            name="Reaction",
        ),
    ]
