# Generated by Django 4.2 on 2025-07-21 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("root", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="admins",
            field=models.ManyToManyField(
                blank=True, related_name="admin_groups", to="root.user"
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="allow_join_requests",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="group",
            name="show_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="group",
            name="show_members",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="GroupJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="root.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_join_requests",
                        to="root.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("group", "user")},
            },
        ),
    ]
